package com.tile.janv.redditviewer.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tile.janv.redditviewer.model.Subreddit;
import com.tile.janv.redditviewer.model.RedditPost;

import com.tile.janv.redditviewer.model.SubredditDao;
import com.tile.janv.redditviewer.model.RedditPostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subredditDaoConfig;
    private final DaoConfig redditPostDaoConfig;

    private final SubredditDao subredditDao;
    private final RedditPostDao redditPostDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subredditDaoConfig = daoConfigMap.get(SubredditDao.class).clone();
        subredditDaoConfig.initIdentityScope(type);

        redditPostDaoConfig = daoConfigMap.get(RedditPostDao.class).clone();
        redditPostDaoConfig.initIdentityScope(type);

        subredditDao = new SubredditDao(subredditDaoConfig, this);
        redditPostDao = new RedditPostDao(redditPostDaoConfig, this);

        registerDao(Subreddit.class, subredditDao);
        registerDao(RedditPost.class, redditPostDao);
    }
    
    public void clear() {
        subredditDaoConfig.getIdentityScope().clear();
        redditPostDaoConfig.getIdentityScope().clear();
    }

    public SubredditDao getSubredditDao() {
        return subredditDao;
    }

    public RedditPostDao getRedditPostDao() {
        return redditPostDao;
    }

}
