package com.tile.janv.redditviewer.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.tile.janv.redditviewer.model.RedditPost;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REDDIT_POST".
*/
public class RedditPostDao extends AbstractDao<RedditPost, Long> {

    public static final String TABLENAME = "REDDIT_POST";

    /**
     * Properties of entity RedditPost.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RedditId = new Property(1, String.class, "redditId", false, "REDDIT_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property Link = new Property(4, String.class, "link", false, "LINK");
        public final static Property Thumbnail = new Property(5, String.class, "thumbnail", false, "THUMBNAIL");
        public final static Property Permalink = new Property(6, String.class, "permalink", false, "PERMALINK");
        public final static Property SubredditId = new Property(7, Long.class, "subredditId", false, "SUBREDDIT_ID");
    };

    private DaoSession daoSession;

    private Query<RedditPost> subreddit_PostsQuery;

    public RedditPostDao(DaoConfig config) {
        super(config);
    }
    
    public RedditPostDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REDDIT_POST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REDDIT_ID\" TEXT," + // 1: redditId
                "\"TITLE\" TEXT," + // 2: title
                "\"AUTHOR\" TEXT," + // 3: author
                "\"LINK\" TEXT," + // 4: link
                "\"THUMBNAIL\" TEXT," + // 5: thumbnail
                "\"PERMALINK\" TEXT," + // 6: permalink
                "\"SUBREDDIT_ID\" INTEGER);"); // 7: subredditId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REDDIT_POST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RedditPost entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String redditId = entity.getRedditId();
        if (redditId != null) {
            stmt.bindString(2, redditId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(5, link);
        }
 
        String thumbnail = entity.getThumbnail();
        if (thumbnail != null) {
            stmt.bindString(6, thumbnail);
        }
 
        String permalink = entity.getPermalink();
        if (permalink != null) {
            stmt.bindString(7, permalink);
        }
 
        Long subredditId = entity.getSubredditId();
        if (subredditId != null) {
            stmt.bindLong(8, subredditId);
        }
    }

    @Override
    protected void attachEntity(RedditPost entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RedditPost readEntity(Cursor cursor, int offset) {
        RedditPost entity = new RedditPost( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // redditId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // author
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // link
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // thumbnail
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // permalink
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7) // subredditId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RedditPost entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRedditId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLink(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setThumbnail(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPermalink(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSubredditId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RedditPost entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RedditPost entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "posts" to-many relationship of Subreddit. */
    public List<RedditPost> _querySubreddit_Posts(Long subredditId) {
        synchronized (this) {
            if (subreddit_PostsQuery == null) {
                QueryBuilder<RedditPost> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SubredditId.eq(null));
                subreddit_PostsQuery = queryBuilder.build();
            }
        }
        Query<RedditPost> query = subreddit_PostsQuery.forCurrentThread();
        query.setParameter(0, subredditId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSubredditDao().getAllColumns());
            builder.append(" FROM REDDIT_POST T");
            builder.append(" LEFT JOIN SUBREDDIT T0 ON T.\"SUBREDDIT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RedditPost loadCurrentDeep(Cursor cursor, boolean lock) {
        RedditPost entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Subreddit subreddit = loadCurrentOther(daoSession.getSubredditDao(), cursor, offset);
        entity.setSubreddit(subreddit);

        return entity;    
    }

    public RedditPost loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RedditPost> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RedditPost> list = new ArrayList<RedditPost>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RedditPost> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RedditPost> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
